### PR TITLE
Adds 404 page

### LINKED ISSUE #484: Default 404 Page Content and User Page Content
We should include a default 404 page mirroring the content that they have on the current live 404 page and set that as the default 404 page to be used.  

Additional we can modify the user page to include links to help documentation as well as Status information about the services we use including Pantheon.

### PR DESCRIPTION
**Pull request by jacob-korf**
Closes https://github.com/CuBoulder/tiamat-theme/issues/484. Adds the implementation of the 404 page.

### CODE REVIEW

**Review by patrickbrown-io — APPROVED** [review]
Installs without issue, automatically presents 404 image on Page Not Found

**Comment by timurtripp** [comment]
Sister PR in: [tiamat-theme](https://github.com/CuBoulder/tiamat-theme/pull/493)

**Review by timurtripp — APPROVED** [review]

**Comment by timurtripp** [comment]
Potentially needs an update hook before merging. I only tested and approved how it works on a clean install.

**Comment by timurtripp** [comment]
Let me know if you'd like an update review and I'll try and provide that.

**Comment by timurtripp** [comment]
Consider adding an update description. Otherwise looks good! Ran without issue.
Screen Shot 2023-10-10 at 10 38 16 AM

**Pull request merged**
