### PR TITLE
refactor code to be reusable elsewhere

### LINKED ISSUE #14: Use namespace and class
In order to use this module's code in a drush command in development, see CuBoulder/ucb_drush_commands#1, it is needed to refactor this module's code so that it can be reused in that other repo.

### PR DESCRIPTION
**Pull request by AlanBCole**
Refactored code to be able to grab it easily in ucb_drush_commands. See CuBoulder/ucb_drush_commands#1

closes #14

### CODE REVIEW

**Comment by timurtripp** [comment]
Going to chat with @AlanBCole about services in Drupal 10 and how they can be used to call functions in one module from another.

**Comment by timurtripp** [comment]
This looks good, thanks for redoing as a service. Going to test on a clean install.

**Review by timurtripp — CHANGES_REQUESTED** [review]
The static method calls
```php
DefaultContent::create_homepage();
DefaultContent::create_404_page();
```
are throwing an error. Get the instance of the service instead using
```php
\Drupal::service('ucb_default_content')
```

**Comment by AlanBCole** [comment]
No problem. Thanks for the help!

**Review by timurtripp — CHANGES_REQUESTED** [review]
Still getting an error related to the order of the arguments in the services.yml not matching the order of the arguments in the class constructor:
```
 [error]  TypeError: Drupal\ucb_default_content\DefaultContent::__construct(): Argument #1 ($config_factory) must be of type Drupal\Core\Config\ConfigFactoryInterface, Drupal\Core\Logger\LoggerChannelFactory given in Drupal\ucb_default_content\DefaultContent->__construct() (line 40 of /app/web/modules/custom/ucb_default_content/src/DefaultContent.php) #0 [internal function]: Drupal\ucb_default_content\DefaultContent->__construct(Object(Drupal\Core\Logger\LoggerChannelFactory), Object(Drupal\mysql\Driver\Database\mysql\Connection), Object(Drupal\Core\Config\ConfigFactory))
```

Also it looks like the Drupal convention is to use camel case for methods inside a class, would you mind changing it over? I recommend the Drupal extension for VS Code as it flags things like this and can automatically fix some of them.

**Review by timurtripp — APPROVED** [review]
Tested and working on a clean install (10.2.7). Thanks for making these changes!

**Pull request merged**
